set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RRESP[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[58]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[54]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[62]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_BRESP[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[47]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[60]}]
set_property MARK_DEBUG true [get_nets design_1_i/processing_system7_0/S_AXI_ACP_WREADY]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[38]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[50]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[55]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[34]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[37]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[48]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[40]}]
set_property MARK_DEBUG true [get_nets design_1_i/processing_system7_0/S_AXI_ACP_AWREADY]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[56]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[52]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[59]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[53]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[42]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[39]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[45]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[63]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[35]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[49]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[51]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[61]}]
set_property MARK_DEBUG true [get_nets design_1_i/processing_system7_0/S_AXI_ACP_ARREADY]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[43]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[57]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[33]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[36]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[41]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[27]}]
set_property MARK_DEBUG true [get_nets design_1_i/processing_system7_0/S_AXI_ACP_RLAST]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[44]}]
set_property MARK_DEBUG true [get_nets design_1_i/processing_system7_0/S_AXI_ACP_BVALID]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_BRESP[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[46]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RRESP[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[32]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[25]}]
set_property MARK_DEBUG true [get_nets design_1_i/processing_system7_0/S_AXI_ACP_RVALID]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WSTRB[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARBURST[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARUSER[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARLEN[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARCACHE[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARSIZE[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[48]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWQOS[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[63]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARPROT[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARSIZE[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[56]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWBURST[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARQOS[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARSIZE[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WID[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[60]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARBURST[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WSTRB[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WID[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWQOS[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARUSER[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[33]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWLOCK[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARUSER[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[58]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARPROT[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWLEN[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARQOS[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWSIZE[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWUSER[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWUSER[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWUSER[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[8]}]
set_property MARK_DEBUG true [get_nets design_1_i/processing_system7_0/S_AXI_ACP_AWVALID]
set_property MARK_DEBUG true [get_nets design_1_i/processing_system7_0/S_AXI_ACP_WVALID]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARLOCK[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[62]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WSTRB[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[47]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[46]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[42]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWID[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARCACHE[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[12]}]
set_property MARK_DEBUG true [get_nets design_1_i/processing_system7_0/S_AXI_ACP_ARVALID]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[38]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[34]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[61]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWPROT[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWLEN[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARUSER[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWID[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWQOS[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWUSER[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[35]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[49]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[44]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WSTRB[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[53]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[25]}]
set_property MARK_DEBUG true [get_nets design_1_i/processing_system7_0/S_AXI_ACP_RREADY]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[15]}]
set_property MARK_DEBUG true [get_nets design_1_i/processing_system7_0/S_AXI_ACP_ACLK]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARQOS[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARLOCK[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARQOS[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWCACHE[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWLEN[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWSIZE[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[54]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[59]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WSTRB[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WSTRB[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWPROT[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWQOS[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[39]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WSTRB[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWUSER[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARPROT[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARID[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARLEN[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWLEN[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[37]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARLEN[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWSIZE[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[43]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WSTRB[5]}]
set_property MARK_DEBUG true [get_nets design_1_i/processing_system7_0/S_AXI_ACP_BREADY]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARCACHE[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWID[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[51]}]
set_property MARK_DEBUG true [get_nets design_1_i/processing_system7_0/S_AXI_ACP_WLAST]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[55]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARLEN[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARUSER[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[45]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[32]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARID[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WID[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWBURST[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[50]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWCACHE[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWCACHE[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARID[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[41]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWPROT[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWCACHE[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[52]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[40]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_ARCACHE[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[36]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[57]}]
set_property MARK_DEBUG true [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_AWLOCK[1]}]

set_property MARK_DEBUG false [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_BID[1]}]
set_property MARK_DEBUG false [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_BID[0]}]
set_property MARK_DEBUG false [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_BID[2]}]
set_property MARK_DEBUG false [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RID[0]}]
set_property MARK_DEBUG false [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RID[1]}]
set_property MARK_DEBUG false [get_nets {design_1_i/processing_system7_0/S_AXI_ACP_RID[2]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_RRESP[0]} {design_1_i/processing_system7_0/S_AXI_ACP_RRESP[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 64 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[0]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[1]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[2]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[3]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[4]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[5]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[6]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[7]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[8]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[9]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[10]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[11]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[12]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[13]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[14]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[15]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[16]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[17]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[18]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[19]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[20]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[21]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[22]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[23]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[24]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[25]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[26]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[27]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[28]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[29]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[30]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[31]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[32]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[33]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[34]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[35]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[36]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[37]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[38]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[39]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[40]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[41]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[42]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[43]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[44]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[45]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[46]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[47]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[48]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[49]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[50]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[51]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[52]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[53]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[54]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[55]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[56]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[57]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[58]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[59]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[60]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[61]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[62]} {design_1_i/processing_system7_0/S_AXI_ACP_WDATA[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_AWLEN[0]} {design_1_i/processing_system7_0/S_AXI_ACP_AWLEN[1]} {design_1_i/processing_system7_0/S_AXI_ACP_AWLEN[2]} {design_1_i/processing_system7_0/S_AXI_ACP_AWLEN[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 3 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_AWSIZE[0]} {design_1_i/processing_system7_0/S_AXI_ACP_AWSIZE[1]} {design_1_i/processing_system7_0/S_AXI_ACP_AWSIZE[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[0]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[1]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[2]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[3]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[4]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[5]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[6]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[7]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[8]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[9]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[10]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[11]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[12]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[13]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[14]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[15]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[16]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[17]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[18]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[19]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[20]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[21]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[22]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[23]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[24]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[25]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[26]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[27]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[28]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[29]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[30]} {design_1_i/processing_system7_0/S_AXI_ACP_ARADDR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 2 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_ARLOCK[0]} {design_1_i/processing_system7_0/S_AXI_ACP_ARLOCK[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_BRESP[0]} {design_1_i/processing_system7_0/S_AXI_ACP_BRESP[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_WSTRB[0]} {design_1_i/processing_system7_0/S_AXI_ACP_WSTRB[1]} {design_1_i/processing_system7_0/S_AXI_ACP_WSTRB[2]} {design_1_i/processing_system7_0/S_AXI_ACP_WSTRB[3]} {design_1_i/processing_system7_0/S_AXI_ACP_WSTRB[4]} {design_1_i/processing_system7_0/S_AXI_ACP_WSTRB[5]} {design_1_i/processing_system7_0/S_AXI_ACP_WSTRB[6]} {design_1_i/processing_system7_0/S_AXI_ACP_WSTRB[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 2 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_ARBURST[0]} {design_1_i/processing_system7_0/S_AXI_ACP_ARBURST[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 3 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_ARPROT[0]} {design_1_i/processing_system7_0/S_AXI_ACP_ARPROT[1]} {design_1_i/processing_system7_0/S_AXI_ACP_ARPROT[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 2 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_AWLOCK[0]} {design_1_i/processing_system7_0/S_AXI_ACP_AWLOCK[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 3 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_AWPROT[0]} {design_1_i/processing_system7_0/S_AXI_ACP_AWPROT[1]} {design_1_i/processing_system7_0/S_AXI_ACP_AWPROT[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 4 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_AWQOS[0]} {design_1_i/processing_system7_0/S_AXI_ACP_AWQOS[1]} {design_1_i/processing_system7_0/S_AXI_ACP_AWQOS[2]} {design_1_i/processing_system7_0/S_AXI_ACP_AWQOS[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 4 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_ARCACHE[0]} {design_1_i/processing_system7_0/S_AXI_ACP_ARCACHE[1]} {design_1_i/processing_system7_0/S_AXI_ACP_ARCACHE[2]} {design_1_i/processing_system7_0/S_AXI_ACP_ARCACHE[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 32 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[0]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[1]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[2]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[3]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[4]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[5]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[6]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[7]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[8]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[9]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[10]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[11]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[12]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[13]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[14]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[15]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[16]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[17]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[18]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[19]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[20]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[21]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[22]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[23]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[24]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[25]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[26]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[27]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[28]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[29]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[30]} {design_1_i/processing_system7_0/S_AXI_ACP_AWADDR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 5 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_ARUSER[0]} {design_1_i/processing_system7_0/S_AXI_ACP_ARUSER[1]} {design_1_i/processing_system7_0/S_AXI_ACP_ARUSER[2]} {design_1_i/processing_system7_0/S_AXI_ACP_ARUSER[3]} {design_1_i/processing_system7_0/S_AXI_ACP_ARUSER[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 2 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_AWBURST[0]} {design_1_i/processing_system7_0/S_AXI_ACP_AWBURST[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 4 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_ARQOS[0]} {design_1_i/processing_system7_0/S_AXI_ACP_ARQOS[1]} {design_1_i/processing_system7_0/S_AXI_ACP_ARQOS[2]} {design_1_i/processing_system7_0/S_AXI_ACP_ARQOS[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 3 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_ARSIZE[0]} {design_1_i/processing_system7_0/S_AXI_ACP_ARSIZE[1]} {design_1_i/processing_system7_0/S_AXI_ACP_ARSIZE[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 4 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_ARLEN[0]} {design_1_i/processing_system7_0/S_AXI_ACP_ARLEN[1]} {design_1_i/processing_system7_0/S_AXI_ACP_ARLEN[2]} {design_1_i/processing_system7_0/S_AXI_ACP_ARLEN[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 4 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_AWCACHE[0]} {design_1_i/processing_system7_0/S_AXI_ACP_AWCACHE[1]} {design_1_i/processing_system7_0/S_AXI_ACP_AWCACHE[2]} {design_1_i/processing_system7_0/S_AXI_ACP_AWCACHE[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 5 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_AWUSER[0]} {design_1_i/processing_system7_0/S_AXI_ACP_AWUSER[1]} {design_1_i/processing_system7_0/S_AXI_ACP_AWUSER[2]} {design_1_i/processing_system7_0/S_AXI_ACP_AWUSER[3]} {design_1_i/processing_system7_0/S_AXI_ACP_AWUSER[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 64 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[0]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[1]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[2]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[3]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[4]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[5]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[6]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[7]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[8]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[9]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[10]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[11]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[12]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[13]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[14]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[15]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[16]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[17]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[18]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[19]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[20]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[21]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[22]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[23]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[24]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[25]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[26]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[27]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[28]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[29]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[30]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[31]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[32]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[33]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[34]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[35]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[36]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[37]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[38]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[39]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[40]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[41]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[42]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[43]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[44]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[45]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[46]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[47]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[48]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[49]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[50]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[51]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[52]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[53]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[54]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[55]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[56]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[57]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[58]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[59]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[60]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[61]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[62]} {design_1_i/processing_system7_0/S_AXI_ACP_RDATA[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list design_1_i/processing_system7_0/S_AXI_ACP_ACLK]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list design_1_i/processing_system7_0/S_AXI_ACP_ARREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list design_1_i/processing_system7_0/S_AXI_ACP_ARVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list design_1_i/processing_system7_0/S_AXI_ACP_AWREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list design_1_i/processing_system7_0/S_AXI_ACP_AWVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list design_1_i/processing_system7_0/S_AXI_ACP_BREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list design_1_i/processing_system7_0/S_AXI_ACP_BVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list design_1_i/processing_system7_0/S_AXI_ACP_RLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list design_1_i/processing_system7_0/S_AXI_ACP_RREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list design_1_i/processing_system7_0/S_AXI_ACP_RVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list design_1_i/processing_system7_0/S_AXI_ACP_WLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list design_1_i/processing_system7_0/S_AXI_ACP_WREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list design_1_i/processing_system7_0/S_AXI_ACP_WVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
